branch-defaults:
  default:
    environment: catalogo-prod
    group_suffix: null
global:
  application_name: catalogo-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
